build:
    environment:
            postgresql: false
            docker: true
    dependencies:
        before:
            - 'source <(curl -fsSL https://raw.githubusercontent.com/phayes/go-scrutinize/master/install-golang)'
            - docker-compose up -d

    tests:
        override:
            -
                command: 'cd $PROJECTPATH && go-scrutinize'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'
                analysis:
                    file: 'checkstyle_report.xml'
                    format: 'general-checkstyle'
