checks:
    go: true

build:
    project_setup:
        override:
            - go build ... -v
    environment:
        go: go1.9.2
    nodes:
        analysis:
            tests:
                override:
                    - go-scrutinizer-run
                    - govet-run
                    -
                        command: go test -race -coverprofile=cover.out
                        coverage:
                            file: 'cover.out'
                            format: 'go-cc'