language: go

go:
  - 1.8

script:
 - go test ./...

notifications:
  email: false

after_success:
    - go get -v github.com/mattn/goveralls
    - goveralls -coverprofile=profile.cov -service=travis-ci