language: go

sudo: required

services:
  - docker

go:
  - 1.8

before_install:
 - docker-compose --file=testing/webtest/docker-compose.yml up -d

script:
 - go test -race github.com/cryptoballot/cryptoballot/cryptoballot -coverprofile=coverage.out -covermode=count
 - go test -race ./...

notifications:
  email: false

after_success:
    - go get -v github.com/mattn/goveralls
    - goveralls -coverprofile=coverage.out -service=travis-ci
