[package]
name = 'cryptoballot'
version = '2.0.0-alpha'
authors = ['phayes <patrick.d.hayes@gmail.com>']
edition = '2018'
decription = 'Cryotgraphically secure online voting. Not production ready'
readme = 'README.md'

[dependencies]
sharks = "0.3"
rand = '0.7.3'
libsecp256k1 = "0.3.5"
ed25519-dalek = { version ="1.0.0-pre.3", features = ["serde"] }
ecies = '0.1.3'
serde_cbor = '0.11.1'
hex = '0.4.1'
num_enum = "0.4.2"
failure = "0.1.6"
sha2 = "0.8.1"
digest = "0.8.1"
rsa-fdh = "0.2.0"
rsa = { version = "0.2.0", features = ["serde1"] }

# TODO: Replace these with something better (that use is_human_readable()) 
hex-serde = "0.1.0" 
hex-buffer-serde = "0.2"

[dependencies.uuid]
version = '0.8.1'
features = [
    'serde',
    'v4',
]

[dependencies.serde]
version = '1.0.104'
features = ['derive']

[dependencies.serde_json]
version = '1.0'
features = ['preserve_order']
