name: Check

on: [push, pull_request]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cargo Cache
      uses: actions/cache@v1
      with:
        path: ~/.cargo
        key: check-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cargo Target Cache
      uses: actions/cache@v1
      with:
        path: target
        key: check-${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Install packages
      run: |
        sudo apt-get -y install libzmq3-dev
        PROTOC_ZIP=protoc-3.11.3-linux-x86_64.zip
        curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.11.3/$PROTOC_ZIP
        sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
        sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
        rm -f $PROTOC_ZIP
        
    - name: Install cargo tools
      run: |
        cargo install cargo-license
        cargo install cargo-audit
      
    - name: Run Cargo check
      run: |
        cargo check
        cargo clippy
        cargo audit
